### ISSUE TITLE
Changing the sleep cover

### ISSUE THREAD

**Issue by tomas-ampueroc** [baskerville/plato#142]
Is there a way to change the sleep cover image from Plato itself or if not how would I go about changing it from the files?

**Comment by baskerville** [comment]
You could append this to your `Settings.toml`:
```toml
[intermission-images]
suspend = "/path/to/the/suspend/image"
```
