### ISSUE TITLE
`line-height` can't be changed on some epub

### ISSUE THREAD

**Issue by bilogic** [baskerville/plato#279]
Hi,

On Plato 0.9.34,

1. I changed `line-height` to a default of 1.5 in `Settings.toml`
2. This has affects on only some epub
3. I tried opening those unaffected ones in koreader and was able to affect their line-height aka line spacing

Any idea how I can troubleshoot? Thank you.

```TOML
selected-library = 0
keyboard-layout = "English"
frontlight = true
wifi = true
inverted = false
sleep-cover = true
auto-share = false
rotation-lock = "portrait"
button-scheme = "natural"
auto-suspend = 30
auto-power-off = 3
time-format = "%H:%M"
date-format = "%A, %B %-d, %Y"
external-urls-queue = "bin/article_fetcher/urls.txt"

[[libraries]]
name = "On Board"
path = "/mnt/onboard"
mode = "database"
sort-method = "added"
first-column = "title-and-author"
second-column = "progress"
thumbnail-previews = true

[[libraries.hooks]]
path = "Articles"
program = "bin/article_fetcher/article_fetcher"
sort-method = "added"
first-column = "title-and-author"
second-column = "progress"

[[libraries]]
name = "Removable"
path = "/mnt/sd"
mode = "database"
sort-method = "opened"
first-column = "title-and-author"
second-column = "progress"
thumbnail-previews = true

[intermissions]
suspend = "logo:"
power-off = "logo:"
share = "logo:"

[[frontlight-presets]]
timestamp = 903

[frontlight-presets.frontlightLevels]
intensity = 12.428735
warmth = 31.927025

[[frontlight-presets]]
timestamp = 1223

[frontlight-presets.frontlightLevels]
intensity = 0.0
warmth = 0.0

[[frontlight-presets]]
timestamp = 1223

[frontlight-presets.frontlightLevels]
intensity = 0.0
warmth = 31.014824

[[frontlight-presets]]
timestamp = 1234

[frontlight-presets.frontlightLevels]
intensity = 12.428735
warmth = 68.6431

[[frontlight-presets]]
timestamp = 1346

[frontlight-presets.frontlightLevels]
intensity = 0.0
warmth = 64.935074

[home]
address-bar = false
navigation-bar = true
max-levels = 3
max-trash-size = 33554432

[reader]
finished = "close"
south-east-corner = "go-to-page"
bottom-right-gesture = "toggle-dithered"
south-strip = "toggle-bars"
west-strip = "previous-page"
east-strip = "next-page"
strip-width = 0.6
corner-width = 0.4
font-path = "/mnt/onboard/fonts"
font-family = "Libertinus Serif"
font-size = 14.0
min-font-size = 5.5
max-font-size = 16.5
text-align = "left"
margin-width = 8
min-margin-width = 0
max-margin-width = 10
line-height = 1.5
continuous-fit-to-width = true
ignore-document-css = false
dithered-kinds = ["jpeg", "jpg", "png", "cbz"]

[reader.paragraph-breaker]
hyphen-penalty = 50
stretch-tolerance = 1.26

[reader.refresh-rate]
regular = 8
inverted = 2

[import]
unshare-trigger = true
startup-trigger = true
metadata-kinds = ["djvu", "epub", "pdf"]
allowed-kinds = ["oxps", "fb2", "xps", "cbz", "djvu", "pdf", "epub"]

[dictionary]
margin-width = 4
font-size = 11.0

[sketch]
save-path = "Sketches"
notify-success = true

[sketch.pen]
size = 2
color = 0
dynamic = true
amplitude = 4.0
min-speed = 0.0
max-speed = 3000.0

[calculator]
font-size = 8.0
margin-width = 2
history-size = 4096

[battery]
warn = 10.0
power-off = 3.0

[frontlight-levels]
intensity = 0.0
warmth = 64.935074
```
