### ISSUE TITLE
Enhancement: universal typography settings

### ISSUE THREAD

**Issue by UnicodeAlt255** [baskerville/plato#40]
I'm not sure if I'm missing something, but neither koreader nor plato seems to have a feature that allows setting the font size, margins, etc. once and having it apply to all books by default. An easy way of implementing this would be to allow changing the default settings.

**Comment by baskerville** [comment]
You can set the default reader settings in `Settings.toml`:
```toml
[reader]
font-family = "Libertinus Serif"
font-size = 10.5
margin-width = 3
line-height = 1.3
```
